Wake On Lan Function
immense/Remotely pull request #455
Opened 2022-01-24 09:05 UTC by lszabados

**Wake On Lan function**

Wake On Lan must be enabled in the BIOS on the selected computer to work.
Another computer on the same subnet and the "Device Group" must be online.

Thank you for your contribution to the Remotely project.  It is required that contributors assign copyright to Immense Networks so we retain full ownership of the project.

This makes it easier for other entities to use the software because they only have to deal with one copyright holder.  It also gives me assurance that we'll be able to make decisions in the future without gathering and consulting all contributors.

While this may seem odd, many open source maintainers practice this.  Here are a couple well-known examples:

- Free Software Foundation: http://www.gnu.org/licenses/why-assign.html
- Microsoft: https://cla.opensource.microsoft.com/

A nice article on the topic can be found here:  https://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx/

By submitting this PR, you agree to the following:

> You hereby assign copyright in this PR's code to the Remotely project and its copyright holder, Immense Networks, to be licensed under the same terms as the rest of the code.  You agree to relinquish any and all copyright interest in the software, to the detriment of your heirs and successors.

2022-07-15 23:33 UTC, lucent-sea commented
Thanks for your work on this.  I know this PR has been open for a long time, and I apologize for the wait.

I'm going to see if I can get permission from Immense to approve PRs.  If so, this will be the first PR I look at.

2023-06-20 18:40 UTC, Nem-z commented
@lucent-sea Sorry to bump such an old PR but I'm searching for a replacement for Teamviewer and Remotely is really great so far. The only thing I'm missing (or I didn't found in the UI) is WOL. Do you have any info on the implementation by any chance?

2023-06-21 18:24 UTC, lucent-sea commented
> @lucent-sea Sorry to bump such an old PR but I'm searching for a replacement for Teamviewer and Remotely is really great so far. The only thing I'm missing (or I didn't found in the UI) is WOL. Do you have any info on the implementation by any chance?

@Nem-z   I apologize.  I spoke too soon about some of my plans for Remotely work.

Currently, all my planned work is focused on the `RemoteControl` library to implement features that will benefit both Remotely and ImmyBot.  I don't have any time allocated for Remotely-only work (which this would fall under).

In addition to getting this PR caught up with master, there are some changes I'd like to see.  I'll leave some comments in case anyone wants to clean it up.

2023-06-21 20:07 UTC, lucent-sea requested changes
Thanks for the PR!  :)  In addition to getting this caught up to master, please address the comments in the review.

2023-06-21 20:07 UTC, bitbound commented on Agent/Program.cs
> +            serviceCollection.AddScoped<WakeOnLanService>();
This should be added to DI under an interface.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/AgentSocket.cs
> +            IDeviceInformationService deviceInfoService,
Again, this should be injected as an interface.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/AgentSocket.cs
> +            _hubConnection.On("WOL", async (string macAddress) =>
Methods (including RPC methods) should be more descriptive, use PascalCasing, and start with a verb.  For example, this could be `WakeDevice` instead of `WOL`.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/DeviceInformationServiceBase.cs
> +                MACAddresses = GetMacAddresses(),
`MACAddress` property should be `PascalCase` (e.g. `MacAddress`).

This property should be a collection (e.g. `string[]`) as opposed to a comma-delimited string.  The entity should have a JSON conversation for storing it in the DB as a string.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/DeviceInformationServiceBase.cs
> +        private string GetMacAddresses(string separator = "") {
This should return a collection (e.g. `IEnumerable<string>` or `string[]`).

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/DeviceInformationServiceBase.cs
> +            foreach (NetworkInterface adapter in nics.Where(c =>
This could be formatted for readability.  E.g.:

```
var onlineNics = nics
    .Where(c => 
        c.NetworkInterfaceType != NetworkInterfaceType.Loopback && 
        c.OperationalStatus == OperationalStatus.Up);

foreach (var adapter in onlineNics)
```

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/DeviceInformationServiceBase.cs
> +                if (unicastAddresses.Any(temp => temp.Address.AddressFamily == AddressFamily.InterNetwork))
Indentation could be reduced below by inverting the check here and using `continue` if met.  Less indentation usually results in less mental load when reasoning about code.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/WakeOnLanService.cs
> +        private IAppLauncher AppLauncher { get; }
These should be private, readonly fields using `_underscoreCamelCase` syntax.

I know a lot of the code in Remotely incorrectly uses private fields.  It was a mistake I made early on and have been since trying to clean up as I go.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/WakeOnLanService.cs
> +        private IAppLauncher AppLauncher { get; }
Actually, it looks like these aren't being used and can be removed.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/WakeOnLanService.cs
> +        public class WOLClass : UdpClient
Public classes should be in their own file.  However, this class isn't used outside this class and can be made private.

Also, class names should be `PascalCase`.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/WakeOnLanService.cs
> +                if (this.Active)
Normally, I'd say this should return a bool to let the caller know if it succeeded.

However, I'm not sure this class is even needed.  `Active` property is the only thing that's `protected` here.  But `SetSocketOption` works regardless of Active state, and I don't think it needs to be called anyway.  See next comment.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/WakeOnLanService.cs
> +        public async Task Wake(string MAC_ADDRESS)
Method parameters should be `camelCase`.

Also, the private implementation method should also be `async Task`, and we should be awaiting `UdpClient.SendAsync`.

2023-06-21 20:07 UTC, bitbound commented on Agent/Services/WakeOnLanService.cs
> +            int reterned_value = client.Send(bytes, 1024);
I believe this can be reduced to the following (worked in my test):

```
var macBytes = Convert.FromHexString(mac);

using var client = new UdpClient();

var macData = Enumerable
    .Repeat(macBytes, 16)
    .SelectMany(x => x);
    
var packet = Enumerable
    .Repeat((byte)0xFF, 6)
    .Concat(macData)
    .ToArray();

var broadcastAddress = System.Net.IPAddress.Parse("255.255.255.255");
// From my understanding. WOL usually uses port 9.
var endpoint = new IPEndPoint(broadcastAddress, 9);
await client.SendAsync(packet, packet.Length, endpoint);
```

2023-06-21 20:07 UTC, bitbound commented on Server/Components/Devices/DeviceCard.razor
> +                                <i class="oi oi-eye" title="View Only"></i>
Title should be changed here.

2023-06-21 20:07 UTC, bitbound commented on Server/Components/Devices/DeviceCard.razor
> +                                <i class="oi oi-eye" title="View Only"></i>
Title should be changed here.

Also, I'm not sure that this is the best place for "Wake All", since I don't think it pertains in any way to this particular computer.  We should probably make a new button toward the top of the page (like where "Select All" and "Refresh" are).

2023-06-21 20:07 UTC, bitbound commented on Server/Components/Devices/DeviceCard.razor.cs
> +        private async Task WakeOnLan(Boolean all) {
`Boolean` should be `bool`.

2023-06-21 20:07 UTC, bitbound commented on Server/Components/Devices/DeviceCard.razor.cs
> +                await CircuitConnection.WOL(Device.ID);
Method should be `PascalCase` and have descriptive name starting with a verb.

2023-06-21 20:07 UTC, bitbound commented on Server/Hubs/CircuitConnection.cs
> +        Task WOL_ALL();
`PascalCase` here, descriptive methods name. etc.

2023-06-21 20:07 UTC, bitbound commented on Server/Hubs/CircuitConnection.cs
> +            var ActiveDevices = devices.Where(c => c.DeviceGroup == device.DeviceGroup && c.OrganizationID == device.OrganizationID).Select(s => s.ID).ToArray();
Local variables should be `camelCase`.

Code should fit comfortably on screen without horizontal scrolling.  Use vertical spacing to make things more readable.  E.g.:

```
var activeDevices = devices
    .Where(c => 
        c.DeviceGroup == device.DeviceGroup && 
        c.OrganizationID == device.OrganizationID)
    .Select(s => s.ID)
    .ToArray();
```

2023-06-21 20:07 UTC, bitbound commented on Server/Hubs/CircuitConnection.cs
> +                string[] MACs = device.MACAddresses.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
Local variables should be `camelCase`.

2023-06-21 20:07 UTC, lucent-sea commented on Server/Hubs/CircuitConnection.cs
> +                break;  // Delete the line so that all active devices will send the Magic packet.
We shouldn't have branching logic that requires source code changes and recompilation.

2023-06-21 20:07 UTC, lucent-sea commented on Server/Hubs/CircuitConnection.cs
> +                foreach (var connection in activeDevices)
We're enumerating collections here more than necessary (multiplicative time cost), resulting in unnecessary CPU use.

I'd recommend enumerating the connections once and arranging them into two dictionaries: one by device ID and one by device group ID.

Within the loop(s), these dictionaries can be used to retrieve devices and device groups with a constant time cost.

2023-06-21 20:07 UTC, lucent-sea commented on Shared/Models/Device.cs
> +        public string MACAddresses { get; set; }
Property names should be `PascalCase`.

Also, this should be a `string[]` or similar collection, with a conversion to JSON in `AppDb.OnModelCreating`.

2023-06-21 22:45 UTC, lucent-sea commented on Agent/Services/WakeOnLanService.cs
> +            int reterned_value = client.Send(bytes, 1024);
Edit: `UdpClient` is disposable, so should be preceded by `using`.

2023-06-22 18:24 UTC, lucent-sea commented
FYI.  I started working on pulling this into master today and should have it ready soon.

2023-06-22 21:18 UTC, lucent-sea commented
Please see cleaned up PR here:  https://github.com/immense/Remotely/pull/667

2023-06-22 21:18 UTC, closed without merging